### ISSUE TITLE
wireframe completion

### ISSUE THREAD

**Issue by melville1** [melville1/coolbeans#1]
## Overview
About page is still blank. 
difference order status vs order history 

## Technical Notes
more clarification on the order status vs order history - 
what font will be used? are we using a background? picture vs color / contrast colors and what colors

**Comment by jtc21am** [comment]
Remember:

Wireframing gives web designers and developers a planned layout of the websites and digital products they're tasked with creating or coding.

This ensures that all the product's elements are in the right place and that the user experience is smooth and intuitive.

Wireframes can also be used to test ideas and ideate interface elements.

By designing wireframes, we provide a visual representation of a website’s structure and user flow. This makes for an effective communication tool as it lets all involved to understand how the website’s elements will interact before any actual coding takes place.
